FROM yzhang71/optasan-1604:latest
RUN apt-get update && apt-get -y install cmake \
	clang-4.0 \
	tar \
	wget \
	sendmail \
	vim \
	git \
	patch \
	pkg-config \
	python3 \
	gcc-4.9 \
	texinfo \
	bison \
	flex \
	software-properties-common \
	fontconfig \
	libfontconfig1-dev
COPY testcases /home/testcases


