FROM yzhang71/optasan-1604:latest
RUN apt-get update && apt-get -y install cmake \
	clang-4.0 \
	tar \
	wget \
	sendmail \
	vim \
	git \
	patch \
	pkg-config \
	fontconfig \
	libfontconfig1-dev
COPY testcases /home/testcases


