
rem NOTE: this batch file is to be run in a Visual Studio command prompt

rem Delete old files
del *.obj
del *.ilk
del *.exe

rem Delete, compile and link files into .obj files in current directory
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcasesupport\main.cpp" "testcasesupport\io.c" "testcasesupport\std_thread.c"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE114_Process_Control\CWE*.c" "testcases\CWE114_Process_Control\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE121_Stack_Based_Buffer_Overflow\s01\CWE*.c" "testcases\CWE121_Stack_Based_Buffer_Overflow\s01\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE121_Stack_Based_Buffer_Overflow\s02\CWE*.c" "testcases\CWE121_Stack_Based_Buffer_Overflow\s02\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE121_Stack_Based_Buffer_Overflow\s03\CWE*.c" "testcases\CWE121_Stack_Based_Buffer_Overflow\s03\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE121_Stack_Based_Buffer_Overflow\s04\CWE*.c" "testcases\CWE121_Stack_Based_Buffer_Overflow\s04\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE121_Stack_Based_Buffer_Overflow\s05\CWE*.c" "testcases\CWE121_Stack_Based_Buffer_Overflow\s05\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE121_Stack_Based_Buffer_Overflow\s06\CWE*.c" "testcases\CWE121_Stack_Based_Buffer_Overflow\s06\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE121_Stack_Based_Buffer_Overflow\s07\CWE*.c" "testcases\CWE121_Stack_Based_Buffer_Overflow\s07\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE121_Stack_Based_Buffer_Overflow\s08\CWE*.c" "testcases\CWE121_Stack_Based_Buffer_Overflow\s08\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE121_Stack_Based_Buffer_Overflow\s09\CWE*.c" "testcases\CWE121_Stack_Based_Buffer_Overflow\s09\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE122_Heap_Based_Buffer_Overflow\s01\CWE*.c" "testcases\CWE122_Heap_Based_Buffer_Overflow\s01\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE122_Heap_Based_Buffer_Overflow\s02\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE122_Heap_Based_Buffer_Overflow\s03\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE122_Heap_Based_Buffer_Overflow\s04\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE122_Heap_Based_Buffer_Overflow\s05\CWE*.c" "testcases\CWE122_Heap_Based_Buffer_Overflow\s05\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE122_Heap_Based_Buffer_Overflow\s06\CWE*.c" "testcases\CWE122_Heap_Based_Buffer_Overflow\s06\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE122_Heap_Based_Buffer_Overflow\s07\CWE*.c" "testcases\CWE122_Heap_Based_Buffer_Overflow\s07\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE122_Heap_Based_Buffer_Overflow\s08\CWE*.c" "testcases\CWE122_Heap_Based_Buffer_Overflow\s08\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE122_Heap_Based_Buffer_Overflow\s09\CWE*.c" "testcases\CWE122_Heap_Based_Buffer_Overflow\s09\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE122_Heap_Based_Buffer_Overflow\s10\CWE*.c" "testcases\CWE122_Heap_Based_Buffer_Overflow\s10\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE122_Heap_Based_Buffer_Overflow\s11\CWE*.c" "testcases\CWE122_Heap_Based_Buffer_Overflow\s11\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE123_Write_What_Where_Condition\CWE*.c" "testcases\CWE123_Write_What_Where_Condition\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE124_Buffer_Underwrite\s01\CWE*.c" "testcases\CWE124_Buffer_Underwrite\s01\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE124_Buffer_Underwrite\s02\CWE*.c" "testcases\CWE124_Buffer_Underwrite\s02\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE124_Buffer_Underwrite\s03\CWE*.c" "testcases\CWE124_Buffer_Underwrite\s03\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE124_Buffer_Underwrite\s04\CWE*.c" "testcases\CWE124_Buffer_Underwrite\s04\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE126_Buffer_Overread\s01\CWE*.c" "testcases\CWE126_Buffer_Overread\s01\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE126_Buffer_Overread\s02\CWE*.c" "testcases\CWE126_Buffer_Overread\s02\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE126_Buffer_Overread\s03\CWE*.c" "testcases\CWE126_Buffer_Overread\s03\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE127_Buffer_Underread\s01\CWE*.c" "testcases\CWE127_Buffer_Underread\s01\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE127_Buffer_Underread\s02\CWE*.c" "testcases\CWE127_Buffer_Underread\s02\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE127_Buffer_Underread\s03\CWE*.c" "testcases\CWE127_Buffer_Underread\s03\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE127_Buffer_Underread\s04\CWE*.c" "testcases\CWE127_Buffer_Underread\s04\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE134_Uncontrolled_Format_String\s01\CWE*.c" "testcases\CWE134_Uncontrolled_Format_String\s01\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE134_Uncontrolled_Format_String\s02\CWE*.c" "testcases\CWE134_Uncontrolled_Format_String\s02\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE134_Uncontrolled_Format_String\s03\CWE*.c" "testcases\CWE134_Uncontrolled_Format_String\s03\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE134_Uncontrolled_Format_String\s04\CWE*.c" "testcases\CWE134_Uncontrolled_Format_String\s04\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE134_Uncontrolled_Format_String\s05\CWE*.c" "testcases\CWE134_Uncontrolled_Format_String\s05\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE134_Uncontrolled_Format_String\s06\CWE*.c" "testcases\CWE134_Uncontrolled_Format_String\s06\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE15_External_Control_of_System_or_Configuration_Setting\CWE*.c" "testcases\CWE15_External_Control_of_System_or_Configuration_Setting\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE176_Improper_Handling_of_Unicode_Encoding\CWE*.c" "testcases\CWE176_Improper_Handling_of_Unicode_Encoding\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE188_Reliance_on_Data_Memory_Layout\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE190_Integer_Overflow\s01\CWE*.c" "testcases\CWE190_Integer_Overflow\s01\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE190_Integer_Overflow\s02\CWE*.c" "testcases\CWE190_Integer_Overflow\s02\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE190_Integer_Overflow\s03\CWE*.c" "testcases\CWE190_Integer_Overflow\s03\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE190_Integer_Overflow\s04\CWE*.c" "testcases\CWE190_Integer_Overflow\s04\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE190_Integer_Overflow\s05\CWE*.c" "testcases\CWE190_Integer_Overflow\s05\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE191_Integer_Underflow\s01\CWE*.c" "testcases\CWE191_Integer_Underflow\s01\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE191_Integer_Underflow\s02\CWE*.c" "testcases\CWE191_Integer_Underflow\s02\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE191_Integer_Underflow\s03\CWE*.c" "testcases\CWE191_Integer_Underflow\s03\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE194_Unexpected_Sign_Extension\s01\CWE*.c" "testcases\CWE194_Unexpected_Sign_Extension\s01\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE194_Unexpected_Sign_Extension\s02\CWE*.c" "testcases\CWE194_Unexpected_Sign_Extension\s02\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE195_Signed_to_Unsigned_Conversion_Error\s01\CWE*.c" "testcases\CWE195_Signed_to_Unsigned_Conversion_Error\s01\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE195_Signed_to_Unsigned_Conversion_Error\s02\CWE*.c" "testcases\CWE195_Signed_to_Unsigned_Conversion_Error\s02\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE196_Unsigned_to_Signed_Conversion_Error\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE197_Numeric_Truncation_Error\s01\CWE*.c" "testcases\CWE197_Numeric_Truncation_Error\s01\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE197_Numeric_Truncation_Error\s02\CWE*.c" "testcases\CWE197_Numeric_Truncation_Error\s02\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE222_Truncation_of_Security_Relevant_Information\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE223_Omission_of_Security_Relevant_Information\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE226_Sensitive_Information_Uncleared_Before_Release\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE23_Relative_Path_Traversal\s01\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE23_Relative_Path_Traversal\s02\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE23_Relative_Path_Traversal\s03\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE23_Relative_Path_Traversal\s04\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE23_Relative_Path_Traversal\s05\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE242_Use_of_Inherently_Dangerous_Function\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE244_Heap_Inspection\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE247_Reliance_on_DNS_Lookups_in_Security_Decision\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE252_Unchecked_Return_Value\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE253_Incorrect_Check_of_Function_Return_Value\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE256_Plaintext_Storage_of_Password\CWE*.c" "testcases\CWE256_Plaintext_Storage_of_Password\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE259_Hard_Coded_Password\CWE*.c" "testcases\CWE259_Hard_Coded_Password\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE272_Least_Privilege_Violation\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE273_Improper_Check_for_Dropped_Privileges\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE284_Improper_Access_Control\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE319_Cleartext_Tx_Sensitive_Info\CWE*.c" "testcases\CWE319_Cleartext_Tx_Sensitive_Info\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE321_Hard_Coded_Cryptographic_Key\CWE*.c" "testcases\CWE321_Hard_Coded_Cryptographic_Key\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE325_Missing_Required_Cryptographic_Step\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE327_Use_Broken_Crypto\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE328_Reversible_One_Way_Hash\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE338_Weak_PRNG\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE364_Signal_Handler_Race_Condition\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE366_Race_Condition_Within_Thread\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE367_TOC_TOU\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE369_Divide_by_Zero\s01\CWE*.c" "testcases\CWE369_Divide_by_Zero\s01\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE369_Divide_by_Zero\s02\CWE*.c" "testcases\CWE369_Divide_by_Zero\s02\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE36_Absolute_Path_Traversal\s01\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE36_Absolute_Path_Traversal\s02\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE36_Absolute_Path_Traversal\s03\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE36_Absolute_Path_Traversal\s04\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE36_Absolute_Path_Traversal\s05\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE377_Insecure_Temporary_File\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE390_Error_Without_Action\CWE*.c" "testcases\CWE390_Error_Without_Action\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE391_Unchecked_Error_Condition\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE396_Catch_Generic_Exception\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE397_Throw_Generic_Exception\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE398_Poor_Code_Quality\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE400_Resource_Exhaustion\s01\CWE*.c" "testcases\CWE400_Resource_Exhaustion\s01\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE400_Resource_Exhaustion\s02\CWE*.c" "testcases\CWE400_Resource_Exhaustion\s02\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE401_Memory_Leak\s01\CWE*.c" "testcases\CWE401_Memory_Leak\s01\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE401_Memory_Leak\s02\CWE*.c" "testcases\CWE401_Memory_Leak\s02\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE401_Memory_Leak\s03\CWE*.c" "testcases\CWE401_Memory_Leak\s03\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE404_Improper_Resource_Shutdown\CWE*.c" "testcases\CWE404_Improper_Resource_Shutdown\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE415_Double_Free\s01\CWE*.c" "testcases\CWE415_Double_Free\s01\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE415_Double_Free\s02\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE416_Use_After_Free\CWE*.c" "testcases\CWE416_Use_After_Free\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE426_Untrusted_Search_Path\CWE*.c" "testcases\CWE426_Untrusted_Search_Path\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE427_Uncontrolled_Search_Path_Element\CWE*.c" "testcases\CWE427_Uncontrolled_Search_Path_Element\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE440_Expected_Behavior_Violation\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE457_Use_of_Uninitialized_Variable\s01\CWE*.c" "testcases\CWE457_Use_of_Uninitialized_Variable\s01\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE457_Use_of_Uninitialized_Variable\s02\CWE*.c" "testcases\CWE457_Use_of_Uninitialized_Variable\s02\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE459_Incomplete_Cleanup\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE464_Addition_of_Data_Structure_Sentinel\CWE*.c" "testcases\CWE464_Addition_of_Data_Structure_Sentinel\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE467_Use_of_sizeof_on_Pointer_Type\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE468_Incorrect_Pointer_Scaling\CWE*.c" "testcases\CWE468_Incorrect_Pointer_Scaling\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE469_Use_of_Pointer_Subtraction_to_Determine_Size\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE475_Undefined_Behavior_for_Input_to_API\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE476_NULL_Pointer_Dereference\CWE*.c" "testcases\CWE476_NULL_Pointer_Dereference\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE478_Missing_Default_Case_in_Switch\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE479_Signal_Handler_Use_of_Non_Reentrant_Function\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE480_Use_of_Incorrect_Operator\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE481_Assigning_Instead_of_Comparing\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE482_Comparing_Instead_of_Assigning\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE483_Incorrect_Block_Delimitation\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE484_Omitted_Break_Statement_in_Switch\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE500_Public_Static_Field_Not_Final\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE506_Embedded_Malicious_Code\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE510_Trapdoor\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE511_Logic_Time_Bomb\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE526_Info_Exposure_Environment_Variables\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE534_Info_Exposure_Debug_Log\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE535_Info_Exposure_Shell_Error\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE546_Suspicious_Comment\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE561_Dead_Code\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE562_Return_of_Stack_Variable_Address\CWE*.c" "testcases\CWE562_Return_of_Stack_Variable_Address\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE563_Unused_Variable\CWE*.c" "testcases\CWE563_Unused_Variable\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE570_Expression_Always_False\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE571_Expression_Always_True\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE587_Assignment_of_Fixed_Address_to_Pointer\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE588_Attempt_to_Access_Child_of_Non_Structure_Pointer\CWE*.c" "testcases\CWE588_Attempt_to_Access_Child_of_Non_Structure_Pointer\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE590_Free_Memory_Not_on_Heap\s01\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE590_Free_Memory_Not_on_Heap\s02\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE590_Free_Memory_Not_on_Heap\s03\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE590_Free_Memory_Not_on_Heap\s04\CWE*.c" "testcases\CWE590_Free_Memory_Not_on_Heap\s04\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE590_Free_Memory_Not_on_Heap\s05\CWE*.c" "testcases\CWE590_Free_Memory_Not_on_Heap\s05\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE591_Sensitive_Data_Storage_in_Improperly_Locked_Memory\CWE*.c" "testcases\CWE591_Sensitive_Data_Storage_in_Improperly_Locked_Memory\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE605_Multiple_Binds_Same_Port\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE606_Unchecked_Loop_Condition\CWE*.c" "testcases\CWE606_Unchecked_Loop_Condition\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE615_Info_Exposure_by_Comment\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE617_Reachable_Assertion\CWE*.c" "testcases\CWE617_Reachable_Assertion\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE620_Unverified_Password_Change\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE665_Improper_Initialization\CWE*.c" "testcases\CWE665_Improper_Initialization\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE666_Operation_on_Resource_in_Wrong_Phase_of_Lifetime\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE667_Improper_Locking\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE672_Operation_on_Resource_After_Expiration_or_Release\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE674_Uncontrolled_Recursion\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE675_Duplicate_Operations_on_Resource\CWE*.c" "testcases\CWE675_Duplicate_Operations_on_Resource\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE676_Use_of_Potentially_Dangerous_Function\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE680_Integer_Overflow_to_Buffer_Overflow\CWE*.c" "testcases\CWE680_Integer_Overflow_to_Buffer_Overflow\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE681_Incorrect_Conversion_Between_Numeric_Types\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE685_Function_Call_With_Incorrect_Number_of_Arguments\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE688_Function_Call_With_Incorrect_Variable_or_Reference_as_Argument\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE690_NULL_Deref_From_Return\s01\CWE*.c" "testcases\CWE690_NULL_Deref_From_Return\s01\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE690_NULL_Deref_From_Return\s02\CWE*.c" "testcases\CWE690_NULL_Deref_From_Return\s02\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE758_Undefined_Behavior\CWE*.c" "testcases\CWE758_Undefined_Behavior\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE761_Free_Pointer_Not_at_Start_of_Buffer\CWE*.c" "testcases\CWE761_Free_Pointer_Not_at_Start_of_Buffer\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE762_Mismatched_Memory_Management_Routines\s01\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE762_Mismatched_Memory_Management_Routines\s02\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE762_Mismatched_Memory_Management_Routines\s03\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE762_Mismatched_Memory_Management_Routines\s04\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE762_Mismatched_Memory_Management_Routines\s05\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE762_Mismatched_Memory_Management_Routines\s06\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE762_Mismatched_Memory_Management_Routines\s07\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE773_Missing_Reference_to_Active_File_Descriptor_or_Handle\CWE*.c" "testcases\CWE773_Missing_Reference_to_Active_File_Descriptor_or_Handle\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE775_Missing_Release_of_File_Descriptor_or_Handle\CWE*.c" "testcases\CWE775_Missing_Release_of_File_Descriptor_or_Handle\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE780_Use_of_RSA_Algorithm_Without_OAEP\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE785_Path_Manipulation_Function_Without_Max_Sized_Buffer\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE789_Uncontrolled_Mem_Alloc\s01\CWE*.c" "testcases\CWE789_Uncontrolled_Mem_Alloc\s01\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE789_Uncontrolled_Mem_Alloc\s02\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE78_OS_Command_Injection\s01\CWE*.c" "testcases\CWE78_OS_Command_Injection\s01\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE78_OS_Command_Injection\s02\CWE*.c" "testcases\CWE78_OS_Command_Injection\s02\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE78_OS_Command_Injection\s03\CWE*.c" "testcases\CWE78_OS_Command_Injection\s03\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE78_OS_Command_Injection\s04\CWE*.c" "testcases\CWE78_OS_Command_Injection\s04\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE78_OS_Command_Injection\s05\CWE*.c" "testcases\CWE78_OS_Command_Injection\s05\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE78_OS_Command_Injection\s06\CWE*.c" "testcases\CWE78_OS_Command_Injection\s06\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE78_OS_Command_Injection\s07\CWE*.c" "testcases\CWE78_OS_Command_Injection\s07\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE78_OS_Command_Injection\s08\CWE*.c" "testcases\CWE78_OS_Command_Injection\s08\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE78_OS_Command_Injection\s09\CWE*.c" "testcases\CWE78_OS_Command_Injection\s09\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE832_Unlock_of_Resource_That_is_Not_Locked\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE835_Infinite_Loop\CWE*.c" 
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE843_Type_Confusion\CWE*.c" "testcases\CWE843_Type_Confusion\CWE*.cpp"
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE90_LDAP_Injection\CWE*.c" "testcases\CWE90_LDAP_Injection\CWE*.cpp"
cl /FeTestcases *.obj /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo
